version = 'v1'
name = 'qemu_2'
server_url = 'http://10.0.2.2:25551'
run_folder = '/run/ankaios/'
insecure = true
runtimes = [ 'podman' ]
tags = { 'host' = 'linaro', 'vm' = 'qemu_2', 'arch' = 'aarch64' }
